"""
Split preprocessed IAM line images into train/val/test under ./data/IAM_pre.

Source layout (already pre-cropped, resized images):
    data_raw/IAM_pre/
        images/                # <id>.jpg files (e.g., a01-000u-00.jpg)
        splits/
            tr_h128.lst        # train image list
            va_h128.lst        # val image list
            te_h128.lst        # test image list

The script copies images according to the split lists and writes labels.txt for
each split by looking up text from existing IAM labels (generated by
prepare_iam.py) under ./data/IAM/{train,val,test}/labels.txt.

実行コマンド: python data_raw/prepare_iam_pre.py --src data_raw/IAM_pre --dst data/IAM_pre --label-root data/IAM
"""
import argparse
import shutil
import re
from pathlib import Path
from typing import Dict, Iterable, List


SPLIT_FILES = {"train": "tr_h128.lst", "val": "va_h128.lst", "test": "te_h128.lst"}




def load_labels(label_files: Iterable[Path], keep_space: bool) -> Dict[str, str]:
    """Load id->text mapping from IAM labels.txt files."""
    mapping: Dict[str, str] = {}
    for path in label_files:
        if not path.exists():
            continue
        with path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n\r")
                if not line:
                    continue
                parts = line.split(None, 1)
                if not parts:
                    continue
                img_id = parts[0]
                text = parts[1] if len(parts) > 1 else ""
                mapping[img_id] = text
    return mapping


def read_split_list(path: Path) -> List[str]:
    """Read list file and return image ids (basename without extension)."""
    ids: List[str] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            ids.append(Path(line).stem)
    return ids


def prepare_iam_pre(src_root: Path, dst_root: Path, label_root: Path, keep_space: bool) -> None:
    src_images = src_root / "images"
    src_splits = src_root / "splits"
    dst_root.mkdir(parents=True, exist_ok=True)

    label_files = [
        label_root / "train" / "labels.txt",
        label_root / "val" / "labels.txt",
        label_root / "test" / "labels.txt",
    ]
    label_map = load_labels(label_files, keep_space=keep_space)
    if not label_map:
        raise FileNotFoundError(
            f"No labels loaded. Expected IAM labels at {label_root}/(train|val|test)/labels.txt"
        )

    for split, split_filename in SPLIT_FILES.items():
        split_path = src_splits / split_filename
        if not split_path.exists():
            raise FileNotFoundError(f"Split file not found: {split_path}")

        out_images = dst_root / split / "images"
        out_images.mkdir(parents=True, exist_ok=True)
        out_labels = dst_root / split / "labels.txt"

        ids = read_split_list(split_path)
        missing_labels = 0
        missing_images = 0
        label_lines: List[str] = []

        for img_id in ids:
            src_img = src_images / f"{img_id}.jpg"
            dst_img = out_images / f"{img_id}.jpg"
            if not src_img.exists():
                missing_images += 1
            else:
                shutil.copy2(src_img, dst_img)

            text = label_map.get(img_id, "")
            if text == "":
                missing_labels += 1
            label_lines.append(f"{img_id} {text}".rstrip() + "\n")

        with out_labels.open("w", encoding="utf-8") as f:
            f.writelines(label_lines)

        print(
            f"[{split}] wrote {len(ids)} samples to {out_images} "
            f"(missing images: {missing_images}, missing labels: {missing_labels})"
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Split IAM_pre into train/val/test under data/IAM_pre.")
    parser.add_argument(
        "--src",
        default="data_raw/IAM_pre",
        type=Path,
        help="Root directory containing images/ and splits/ (default: data_raw/IAM_pre)",
    )
    parser.add_argument(
        "--dst",
        default="data/IAM_pre",
        type=Path,
        help="Output root directory (default: data/IAM_pre)",
    )
    parser.add_argument(
        "--label-root",
        default="data/IAM",
        type=Path,
        help="Directory that already has train/val/test/labels.txt generated from IAM.",
    )
    parser.add_argument(
        "--keep-space",
        action="store_true",
        help="Keep spaces when normalizing labels (default: remove spaces).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    prepare_iam_pre(args.src, args.dst, args.label_root, keep_space=args.keep_space)
